version: '3'

services:
  phpstorm:
    container_name: phpstorm
    build:
      context: ./
      dockerfile: additional/phpstorm/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - phpstorm-config:/home/magento/.PhpStorm2018.3
      - phpstorm-java:/home/magento/.java
      - src-volume:/var/www/html
    environment:
      - DISPLAY=host.docker.internal:0
networks:
  default:
    external:
      name: env_default
volumes:
  src-volume:
  phpstorm-config:
  phpstorm-java:
