version: '2'

services:
  web:
    container_name: magento2web
    restart: always
    build: .
    ports:
      - "8000:80"
      - "8443:443"
      - "2222:22"
  db:
    container_name: magento2db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: magento
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    ports:
      - "3306:3306"
    volumes:
      - "./etc/mysql:/etc/mysql/conf.d"
